name: Deploy to betashop

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy sur la VM Azure
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 40.85.221.73
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          known_hosts: |
            |1|LoyRLRQIDpzTNdXieRxROyV/4PE=|crqQ3q7A+gX2MXgDyDfml4Q80xQ= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWBEDjarx02ND6351K6Rx2wYzrqK6pHEG0gR9yrPyP2j+mNctzCe0AOuQsCwzP6s4MgwFaV0Uk71ICMWFxZL640Ozh7gyMvcWvAH9UnO5v6Jl7Z57Gun0i2FVGI1yvIFJIfvYeiyA47cTfW43AToNCA5m7u9nFcLLV1CNKr7OxTze5nYp43R/b4Rs4WQNKRhXqP5IMFCVUXZf+FcpTpmm7uY2OppdAPY9wTGmK2+08dka01gZwb7GhhTdkE+YUE+UixFuNgRyXQsXia4J68VieV+neBH6I7qmi2Cg0qcXo70FNIoA+R7UucVQbfbvHOeDRO5sR+BY2ZbzvYr/j7YkE5wqI4Re8zUy50bqkiS6+WigzqQilWlh+sQTEt1+wBvQMWf54zM1h+u0UjYYhGkvtkZNdsgy2OdPlTfT3XVOrOdHa7ZUN9zCRjcP6U6RDA0mtJ98M1VGxbWuM0mAgnd9vEcFDRVqO9Wys9jgTtZQ5Eu2+xsLTPq/ILlxF96vnPW8=
            |1|d5kSbGq1+9v771QyXoD7EfP4Bfk=|OX+eTVJP/oi8E3Xbmx7m686JjZw= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAGPj1KHvB5TE6xLy9/Oe6JN9fKCANXnJQlKqrgaWCQ9
          script: /home/azureuser/deploy.sh
